#@TYPE: Machine
#@NAME: Apple iPod Touch
#@DESCRIPTION: Machine configuration for the Apple iPod Touch

TARGET_ARCH = "arm"
PACKAGE_EXTRA_ARCHS = "armv4 armv4t armv5e armv5te"

XSERVER = "xserver-kdrive-fbdev"

MACHINE_FEATURES = "kernel26 apm usbgadget"
