SDK_ARCH = "aarch64"
SDK_OS = "darwin21"

SOLIBS:darwin21 = ".dylib"
SOLIBSDEV:darwin21 = ".dylibbroken"

PREFERRED_PROVIDER_virtual/nativesdk-${SDK_PREFIX}libc-for-gcc = "nativesdk-osx-runtime"
PREFERRED_PROVIDER_virtual/nativesdk-${SDK_PREFIX}libc-initial = "nativesdk-osx-runtime"
PREFERRED_PROVIDER_virtual/${SDK_PREFIX}binutils = "cctools-port-crosssdk"
PREFERRED_PROVIDER_virtual/nativesdk-libc = "nativesdk-osx-runtime"
PREFERRED_PROVIDER_virtual/nativesdk-libintl = "nativesdk-osx-runtime"
PREFERRED_PROVIDER_virtual/nativesdk-libiconv = "nativesdk-osx-runtime"

SDKUSE_NLS = "no"
SDKIMAGE_LINGUAS = ""
SDK_DEPENDS:remove = "nativesdk-glibc-locale nativesdk-qemuwrapper-cross"

SDKPKGSUFFIX = "nativesdk-darwin"

OSX_TOOLCHAIN_OPTIONS = " \
    -mmacosx-version-min=12.3 \
    -L${STAGING_DIR_TARGET}${SDKPATHNATIVE}/usr/lib \
    -L${STAGING_DIR_TARGET}${SDKPATHNATIVE}/runtime/usr/lib \
    -L${STAGING_DIR_TARGET}${SDKPATHNATIVE}/runtime/usr/lib/system \
"

TOOLCHAIN_OPTIONS:append:darwin21 = " \
    ${OSX_TOOLCHAIN_OPTIONS}"
TOOLCHAIN_OPTIONS:append:class-cross-canadian = " \
    ${OSX_TOOLCHAIN_OPTIONS}"

# Remove -rpath-link
BUILDSDK_LDFLAGS = " \
    -L${STAGING_LIBDIR} \
    -Wl,-rpath,${libdir} \
    -L${STAGING_DIR_HOST}${base_libdir} \
    -Wl,-rpath,${base_libdir} \
"

MACHINEOVERRIDES .= ":darwinsdk"
